<?xml version="1.0"?>
<package format="2">
    <name>legged_wbc</name>
    <version>0.0.0</version>
    <description>Whole body control</description>
    <maintainer email="liaoqiayuan@gmail.com">Qiayuan Liao</maintainer>

    <license>BSD</license>
    <author email="liaoqiayuan@gmail.com">Qiayuan Liao</author>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <build_depend>cmake_clang_tools</build_depend>

    <build_depend>tf2</build_depend>
    <depend>wbc_centroidal_model</depend>
    <depend>ocs2_sqp</depend>
    <depend>ocs2_ipm</depend>
    <depend>ocs2_legged_robot</depend>
    <depend>qpoases_cmake</depend>
    <depend>pinocchio</depend>
    <depend>magnecko_mpc</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>
