name: Build and Test legged control

on:
  push:
    branches: [ ros2-jazzy-devel ]
  pull_request:
    branches: [ ros2-jazzy-devel ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04
    container:
      image: ubuntu:24.04

    steps:
    - name: Environment Info
      run: |
        apt-get update 
        apt-get install -y lsb-release
        pwd
        uname -r
        lsb_release -a

    - name: System deps
      run: |
        apt-get update
        apt-get install -y git ninja-build liburdfdom-dev liboctomap-dev libassimp-dev liblcm-dev checkinstall wget rsync curl

    - name: ROS Jazzy installation
      run: |
        locale
        apt update
        apt install -y locales
        locale-gen en_US en_US.UTF-8
        update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
        export LANG=en_US.UTF-8
        locale
        apt install -y software-properties-common
        add-apt-repository universe
        apt update
        export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}')
        curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb"
        dpkg -i /tmp/ros2-apt-source.deb
        apt update
        apt install -y ros-dev-tools
        apt update
        apt upgrade -y
        apt install -y ros-jazzy-desktop
        apt install -y ros-jazzy-ros-base
        apt install -y \
          ros-jazzy-controller-interface \
          ros-jazzy-hardware-interface \
          ros-jazzy-realtime-tools \
          ros-jazzy-joint-state-broadcaster \
          ros-jazzy-imu-sensor-broadcaster \
          ros-jazzy-gazebo-ros2-control
        
    - name: Pinocchio from robotpkg
      run: |
        curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc | tee /etc/apt/keyrings/robotpkg.asc
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" | tee /etc/apt/sources.list.d/robotpkg.list
        apt-get update
        apt-get install -y robotpkg-coal robotpkg-pinocchio
        echo "CMAKE_PREFIX_PATH=/opt/openrobots:${CMAKE_PREFIX_PATH}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/opt/openrobots/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV

    - name: Checkout dependencies
      run: |
        git clone -b ros2 https://github.com/idra-lab/ocs2.git src/ocs2
        git clone -b ros2 https://github.com/leggedrobotics/ocs2_robotic_assets.git src/ocs2_robotic_assets

    - uses: actions/checkout@v4
      with: 
        ref: ros2-jazzy-devel
        path: src/legged_control 

    - name: Rosdep
      run: |
        rosdep init || true
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build Release
      shell: bash
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon build --packages-up-to legged_controllers legged_unitree_description legged_gazebo legged_unitree_hw  
